# Generated by Django 4.1.10 on 2023-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algoapp', '0002_businessdetails_our_clients_newsletter_users_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
