# Generated by Django 4.1.10 on 2023-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algoapp', '0003_alter_blog_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter_users',
            name='user',
        ),
        migrations.AddField(
            model_name='newsletter_users',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
    ]
